version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: biotec-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=biotec_lab
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - biotec-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biotec-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/biotec_lab
      - DB_NAME=biotec_lab
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - biotec-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biotec-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    networks:
      - biotec-network

volumes:
  mongodb_data:

networks:
  biotec-network:
    driver: bridge